import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { FaShoppingBasket } from "react-icons/fa";
import Image from "next/image";
import google from "@/public/assets/google.png";
import feira from "@/public/assets/feira.png";
export default function Home() {
  return (
    <>
      <Head>
        <title>SmartList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={styles.containerMain}>
        <div className={styles.head}>
          <span className={styles.logo}>
            <FaShoppingBasket size={80} color="#2ecc8a" />
          </span>
          <h1>SmartList</h1>
        </div>
        <div className={styles.bannerLogin}>
          <Image
            src={feira}
            className={styles.banner}
            alt="imagem da uma sexta de compras com varios legumes"
          />
        </div>

        <div className={styles.body}>
          <div className={styles.textcontainer}>
            <h2 className={styles.text}>
              Organize suas compras <br />
              de forma inteligente
            </h2>
            <p className={styles.paragrafo}>
              A maneira mais simples de gerenciar sua <br />
              lista de mercado.
            </p>
          </div>

          <div className={styles.entrarComGoogle}>
            <span className={styles.google}>
              <Image
                src={google}
                className={styles.img}
                alt="Imagem do google"
              />
            </span>
            <p>Entrar com Google</p>
          </div>
        </div>

        <div className={styles.textFooter}>
          <p>
            Ao entrar, você concorda com nossos<span> termos</span> <br />
            <span> de uso </span> e <span>política de privacidade</span> 
          </p>
        </div>
      </main>
    </>
  );
}
